FROM nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04

# Install necessary build tools and libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    ca-certificates \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip \
    python3-setuptools \
    wget gnupg && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install Jupyter
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install tensorflow==2.6.0 jupyter

# Create a workspace directory
WORKDIR /workspace

# Copy requirements file and install Python dependencies
COPY requirements.txt /tmp/
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements.txt

# Run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=9999", "--no-browser", "--allow-root"]
